// Run after :app:testDebugUnitTest. Fixture is generated by the actual Kotlin emitter.
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import test from 'node:test';
import assert from 'node:assert/strict';
const script = readFileSync(new URL('../android/app/build/reports/lifecycle-dispatch.js', import.meta.url), 'utf8');
function page({ origin = 'https://foodhome.market', visible = true, ready = true, top = true } = {}) {
  const events = [];
  const window = { dispatchEvent: event => events.push(event) };
  window.top = top ? window : {};
  if (ready) window.FoodHomeBridge = { onmessage() {} };
  const context = vm.createContext({ window, location: { origin }, document: { visibilityState: visible ? 'visible' : 'hidden' }, CustomEvent: class {
    constructor(type, { detail }) { this.type = type; this.detail = detail; }
  } });
  return { events, window, context, run: () => vm.runInContext(script, context) };
}
for (const [name, options] of Object.entries({ foreignOrigin: { origin: 'https://evil.invalid' }, http: { origin: 'http://foodhome.market' }, port: { origin: 'https://foodhome.market:444' }, iframe: { top: false }, hidden: { visible: false }, noAdapter: { ready: false } })) {
  test(`does not emit into ${name}`, () => {
    const p = page(options); assert.equal(p.run(), false); assert.equal(p.events.length, 0);
  });
}
test('late adapter and visibility can retry without losing the signals', () => {
  const p = page({ ready: false, visible: false });
  assert.equal(p.run(), false);
  p.window.FoodHomeBridge = { onmessage() {} };
  p.context.document.visibilityState = 'visible';
  assert.equal(p.run(), true);
  assert.deepEqual(p.events.map(e => e.detail.name), ['appResumed', 'permissionChanged']);
  for (const e of p.events) {
    assert.equal(e.type, 'foodhome:native-event');
    assert.equal(Object.keys(e.detail.payload).length, 0);
    assert.equal(e.detail.protocol, 'foodhome.bridge');
    assert.equal(e.detail.version, 1);
  }
});
test('deduplicates in current document, replays after navigation', () => {
  const p = page(); p.run(); p.run(); p.run();
  assert.equal(p.events.length, 2);
  const replacement = page(); replacement.run();
  assert.equal(replacement.events.length, 2);
});
